### ISSUE TITLE
Sort items in nodes by most votes

### ISSUE THREAD

**Issue by tomzx** [learn-anything/learn-anything#1243]
I think it would make sense to sort the items within nodes by their vote count, with the ones having the most being at the top. This will in turn make the tool more valuable to users, as people generally want to look at the most valuable resources first.

As one can see from the image below, currently we do not appear to do any sorting.

![chrome_2018-01-13_21-51-09](https://user-images.githubusercontent.com/188960/34912301-e4f59d54-f8ab-11e7-990d-28d905da19e5.png)

**Comment by nikitavoloboev** [comment]
This feature will be available in the new design we are working on.

There is only one thing we are uncertain about. And that is how do we surface the best results on the top without resorting to having some one resource that is already on the top, stay on the top because it will e the resource most seen thus essentially cementing its position in the ranking. Another issue to solve is that most voted resource may not mean the 'best' resource, so perhaps some curation or moderation by topic experts should take place.

Would love to hear your thoughts @tomzx or anyone else reading the issue on how we can solve this best.

**Comment by Mister-GoodwinLu** [comment]
you could have display 1: Moderation by experts; 2: by common voting; 3. Alphabetical order. Of course, it is hard to get a knowledgable person to vote on these topics

**Comment by nikitavoloboev** [comment]
@Mister-GoodwinLu We think of having something like this. Although the moderation by experts will be mixed in with 'common voting'. As 'certified' experts of certain topics can better curate the best resources as popular resources don't mean 'best' resources. And we want to focus on quality.
