### ISSUE TITLE
Where to add resources help

### ISSUE THREAD

**Issue by mattburman** [learn-anything/learn-anything#1245]
As a user, I want immediately available guidance on where to put my resource, so that I can contribute to Learn Anything's consistency across maps.

Example, I am adding to https://learn-anything.xyz/health/nutrition/keto.
where would this go?: http://lowcarbediem.com/healthy-high-fat-low-carb-foods/
In root or in help? Are there other types of nodes?

I suspect you have some guidance somewhere but I think it should be made more available on the site when contributing.

In some ways, I'm playing devil's advocate as a new user
(obviously I could do some research to find this out where you've written about this elsewhere - I've definitely read it in the past somewhere)

**Comment by nikitavoloboev** [comment]
Hey @mattburman 

Yeah, I agree. This will actually be solved in the new layout we are working on. 

The idea behind is that we are going to split Learn Anything into two parts. One for exploring content (topics). And one for learning a topic. So as a user you explore a graph of nodes of topics to learn and pressing on the topic you get a page of best resources available for learning a topic as curated by community.

The learning page will also be a normal webpage similar to a GitHub list. Where you can then also filter the resources by categories and perhaps more things. But there will be no distinction of `Help` `Basics`, `Talks` and as such because as you said that is confusing.

**Comment by nikitavoloboev** [comment]
Also we are thinking of adding another attribute to resources specifiying `difficulty` of a resource. Ranging from `Basic` to `Intermediate` to `Advanced`. Which again allows you to start learning progressively from `Basic` stuff to more complex stuff. For some topics like `Keto` this will be overkill so I assume most resources there will be `Basic` but for `Machine learning` I think it will make a difference in finding the right resource to learn.

**Comment by nikitavoloboev** [comment]
The new design we are working should ideally solve this issues as the web interface for adding resources and interacting with resources should be much simpler and more akin to a normal web page than a mind map. We will have mind maps for the new `Explore` section of the website where users can explore topics and see connections between them.

The rough design of how we envision the new design will work can be seen here: https://balsamiq.cloud/svp9z/p20pi/r2278
