### ISSUE TITLE
Getting a blank screen on the new setup

### ISSUE THREAD

**Issue by yg** [learn-anything/learn-anything#14]
### Bug 🐞

Getting a blank screen on the new setup

### Steps to Reproduce:

1. Setup the app locally
2. `yarn dev`

![Screenshot from 2020-06-05 11-35-48](https://user-images.githubusercontent.com/61746440/83842562-de625600-a720-11ea-8726-3a6249890f08.png)

```json
{
   "errors":[
      {
         "extensions":{
            "path":"$",
            "code":"access-denied"
         },
         "message":"invalid x-hasura-admin-secret/x-hasura-access-key"
      }
   ]
}
```

**Comment by jletey** [comment]
This is because you don't have the API secret key to access the API endpoint.

Ideally we should have two API keys: one that is read only (for contributors) and one that is read/write (for admins/core devs as well as deploying to production).

@nikitavoloboev and I will discuss the best way to move forward :)
